name: Publish to npm

on:
  release:
    types: [published]

env:
  TAG: ${{ github.event.release.tag_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Replace version in package.json
        shell: bash
        run: |
          if [[ "$OSTYPE" == "darwin"* ]]; then
            find . -name "package.json" -exec sed -i '' "s/\"version\": \".*\"/\"version\": \"${{ env.TAG }}\"/" {} +
          else
            find . -name "package.json" -exec sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.TAG }}\"/" {} +
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Publish skills
        run: npm publish --access public
